### ISSUE TITLE
Migrate package to use typescript

### ISSUE THREAD

**Issue by willmendesneto** [willmendesneto/hex-to-css-filter#2]
The current package is written in typescript. However, we can improve the integration with Editors and IDE's, as also improve the codebase improvements and refactor by migrating the package from JS to TS

**Comment by rtucker88** [comment]
Hey @willmendesneto thanks for merging the types. I could see about taking on this rewrite if you like.

**Comment by willmendesneto** [comment]
Hey @rtucker88 thanks for the ping! 

I didn't check the message previously, so I applied the migration. I'll publish the new major version for the package with the new type changes in a few and I'll share in this issue.

Sorry, mate. Thank you so much for that, I really appreciate!

**Comment by willmendesneto** [comment]
@rtucker88 I just published a new version of the package. Feel free to upgrade your project to use `hex-to-css-filter@2.0.0`
