### ISSUE TITLE
The filter value does not seem to be directly usable

### ISSUE THREAD

**Issue by u3u** [willmendesneto/hex-to-css-filter#7]
## HexToCSSFilter results

values: 
`38.82319683098018,90.86017387724603,4224.811064056966,44.894430956508096,94.93757861883024,100.89169332773609`

called: `6`

loss: `0.117682683559579`

filter: `invert(39%) sepia(91%) saturate(4225%) hue-rotate(162deg) brightness(95%) contrast(101%);`

hex: `#00a4d6`

rgb: `0,164,214`

https://github.com/willmendesneto/hex-to-css-filter/blob/996d0c78ba275b7c16ae3d87821dd044276db563/src/solver.ts#L136

It seems that the filter is based on white, so you need to set the filter to white to take effect.

```diff
- filter: invert(39%) sepia(91%) saturate(4225%) hue-rotate(162deg) brightness(95%) contrast(101%);
+ filter: brightness(0) invert(1) invert(39%) sepia(91%) saturate(4225%) hue-rotate(162deg) brightness(95%) contrast(101%);
```

**Comment by willmendesneto** [comment]
Hi, @u3u . Thanks for raise this issue.

Nice find! I addressed this issue in this commit https://github.com/willmendesneto/hex-to-css-filter/commit/74721fac45f78b3cff03e27ff8935e3752c56334. Please feel free to bump your dependencies to use `hex-to-css-filter@2.0.3`

**Comment by u3u** [comment]
Thanks!
