### ISSUE TITLE
Wrong filter when try convert '#ffffff' color

### ISSUE THREAD

**Issue by dimkajasons** [willmendesneto/hex-to-css-filter#8]
**HexToCSSFilter results**
values: 0.517553073308509,30.866110304298406,432.6968172922908,60.46822764634507,117.29844903999971,100.49939525103152

called: 1

loss: 0

filter: brightness(0) invert(1%) sepia(31%) saturate(433%) hue-rotate(218deg) brightness(117%) contrast(100%);

hex: #ffffff

rgb: 255,255,255

but this filter value looks like black instead of white. Could you please explain above behaviour?

**Comment by dblodorn** [comment]
@willmendesneto 

Heya - so happy to find an npm port of this - having the same issue with lighter colors - basically once we move into the white / off white range

This Codepen - of similar code seems to work with white: [https://codepen.io/sosuke/pen/Pjoqqp](https://codepen.io/sosuke/pen/Pjoqqp)

Again really appreciate this - it's perfect for a client project i'm on.

**Comment by willmendesneto** [comment]
Closing this issue for now, but feel free to reopen it. Thanks for raising that @dimkajasons @dblodorn !!!
